In [1]:
!pip install tweepy

Collecting tweepy
  Downloading tweepy-4.8.0-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 KB 2.5 MB/s eta 0:00:00
Requirement already satisfied: oauthlib<4,>=3.2.0 in /opt/conda/lib/python3.9/site-packages (from tweepy) (3.2.0)
Requirement already satisfied: requests<3,>=2.27.0 in /opt/conda/lib/python3.9/site-packages (from tweepy) (2.27.1)
Collecting requests-oauthlib<2,>=1.2.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests<3,>=2.27.0->tweepy) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests<3,>=2.27.0->tweepy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests<3,>=2.27.0->tweepy) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.9/site-packages (from requests<3,>=2.27.0->tweepy) (2.0.12)
Installing collected packages: requests-oauthlib, tweepy
Successfully installed requests-oauthlib-1.3.1 tweepy-4.8.0

In [8]:
import tweepy
import configparser
import pandas as pd

#read configs
#config = configparser.ConfigParser()
#config.read('config.ini')

api_key = 'eoZsATKpZWb0KqQS93ywspsoT'
api_key_secret = '59h84KKmArMeGYv4IGPE7fndSuFaDSlHzFG5bE2W7Hwt5c0zdY'

access_token = '1499691151259013125-IuJvY6pZK9GIfMDkyYEjOmTn23v9nV'
access_token_secret = 'ZX5pxgraeSOGViSOu2DqZrzwJuBNliDeiwIivfyFZeESW'

auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

In [19]:
num_of_tweets = 200
tweets = []
time = []
likes = []

users = '@dragflickscores OR @thedragflick OR @WorldHockeyNews OR @EnglandHockey OR @PolandHockey'
cursor = tweepy.Cursor(api.search_tweets, q = users, tweet_mode = "extended").items(num_of_tweets)

for t in cursor:
    tweets.append(t.full_text)
    time.append(t.created_at)
    likes.append(t.favorite_count)

df = pd.DataFrame({'tweets':tweets, 'likes':likes, 'time':time})
df

,tweets,likes,time
0,Bir tutkudur #hokey \nYaşa bakılmaz!\n\n@Engla...,5,2022-04-29 12:04:14+00:00
1,@DanTibbitt @UoNLHC @uonmhc @EnglandHockey @Uo...,0,2022-04-29 10:59:58+00:00
2,"@EnglandHockey @WimbledonHC @ExeterUniHC Yet, ...",0,2022-04-29 09:33:03+00:00
3,RT @WorldHockeyNews: #THP Team GB hockey based...,0,2022-04-29 07:45:43+00:00
4,@PolandHockey Lyszczarczyk trying too hard to ...,0,2022-04-29 07:29:38+00:00
...,...,...,...
195,RT @WhitgiftSport: The U16s have followed the ...,0,2022-04-27 15:23:22+00:00
196,RT @MCSOxford: We're National Hockey #Champion...,0,2022-04-27 15:18:41+00:00
197,Good luck to our U18 Hockey boys who are curre...,6,2022-04-27 15:18:33+00:00
198,RT @MCSOxford: We're National Hockey #Champion...,0,2022-04-27 15:09:32+00:00
199,@BradfieldCol @MCSOxford @MCSHockey @EnglandHo...,5,2022-04-27 15:04:18+00:00

In [20]:
df = df[~df.tweets.str.contains("RT")]
df = df.reset_index(drop=True)
df

,tweets,likes,time
0,Bir tutkudur #hokey \nYaşa bakılmaz!\n\n@Engla...,5,2022-04-29 12:04:14+00:00
1,@DanTibbitt @UoNLHC @uonmhc @EnglandHockey @Uo...,0,2022-04-29 10:59:58+00:00
2,"@EnglandHockey @WimbledonHC @ExeterUniHC Yet, ...",0,2022-04-29 09:33:03+00:00
3,@PolandHockey Lyszczarczyk trying too hard to ...,0,2022-04-29 07:29:38+00:00
4,@EnglandHockey Love this ❤️❤️❤️👏👏👏👏,1,2022-04-29 07:23:49+00:00
...,...,...,...
93,@BradfieldCol @MCSOxford @MCSHockey @EnglandHo...,0,2022-04-27 15:30:34+00:00
94,@MCSOxford @MCSHockey @EnglandHockey @Bradfiel...,1,2022-04-27 15:25:55+00:00
95,@WhitgiftSport @EnglandHockey Just how super c...,8,2022-04-27 15:24:39+00:00
96,Good luck to our U18 Hockey boys who are curre...,6,2022-04-27 15:18:33+00:00
97,@BradfieldCol @MCSOxford @MCSHockey @EnglandHo...,5,2022-04-27 15:04:18+00:00

In [21]:
mostlike = df.loc[df.likes.nlargest(5).index]
mostlike

,tweets,likes,time
83,NULS 1st XI have gone and WON the U18’s EH T3 ...,44,2022-04-27 17:58:04+00:00
52,ICYMI: Our 1st XI boys hockey team has won the...,32,2022-04-28 10:10:45+00:00
18,We are very proud to announce that we are one ...,29,2022-04-28 20:26:14+00:00
78,Hockey Facility Development | Preparations wel...,22,2022-04-27 19:14:21+00:00
87,‘come check this’🙌🏑 @Y1Hockey @EnglandHockey 🎵...,20,2022-04-27 17:14:06+00:00